# fly.toml file generated for restless-field-6401 on 2023-03-30T22:21:10+02:00

app = "restless-field-6401"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "cdg"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
